id: afistler
name: "Adam Fistler Services"
url: "https://www.afistler.us.to"

head:
  meta:
    -
      http-equiv: "Content-Type"
      content: "text/html;"
    -
      http-equiv: Language
      content: en
    -
      name: Authors
      content: "Adam Fistler"
    -
      name: "revist-after"
      content: "7 days"
    -
      robots: "index, follow"

fonts:
  - "https://fonts.googleapis.com/css2?family=Brush+Script"
  - "https://fonts.googleapis.com/css2?family=Kalam:wght@400;700&display=swap"

css:
  - "/css/site/main.css"
  - "/css/site/article.css"
  - "/css/site/content.css"
  - "/css/site/display_table.css"
  - "/css/site/header.css"
  - "/css/site/message_box.css"


js:
  - "/js/site/main.js"
  - "https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"
  - "https://cdnjs.cloudflare.com/ajax/libs/js-yaml/4.1.0/js-yaml.min.js"

menus:
  main_menu:
    "Home": "main.home"
    "GoFundMe": "main.go_fund_me"
    "Hypnosis":
      "Professional Experience": "articles.hypnosis.bhc"
      "About Hypnosis": "hypnosis.about_hypnosis"
      "Hypnosis Services": "hypnosis.hypnosis_services"
      "Testimonals": "hypnosis.testimonals"
      "Anger": "hypnosis.anger"
      "Weight Loss": "hypnosis.weight_loss"
      "Smoking Cessation": "hypnosis.smoking_cessation"
    "Addiction Services": "addiction.addiction_services"
    "Astrology": "astrology.astrology"
    "Handwriting Analysis": "graphology.graphology"
    "Technology":
      "Projects": "technology.projects"
      "Artwork": "technology.artwork"
      "Resume": "technology.resume"
    "Upcoming Events": "main.upcoming_events"
    "Articles": "articles.articles"
    "Contact Us": "main.contact_us"

data:
  address:
    street: "Coming Soon"
    city: "South Jersey"
    state: "NJ"
    zipcode: "08104"
  phone: "(856) 209-3350"
  email: "afistler.services@gmail.com"
  footer:
    - "Copyright © 2023 - Adam Fistler Services"
    - "Adam Fistler Services - New Office Coming Soon #{data.phone}"
    - "Serving South Jersey with the latest in hypnosis, addiction alternatives, mindfullness and technology."
    - "South Jersey's Choice for Holisitc Healing"

