id: afistler
name: "Adam Fistler Services"
url: "https://www.afistler.us.to"
template: "templates/afistler.html"
indent: 2

head:
  meta:
    -
      http-equiv: "Content-Type"
      content: "text/html;"
    -
      http-equiv: Language
      content: en
    -
      name: Authors
      content: "Adam Fistler"
    -
      name: "revist-after"
      content: "7 days"
    -
      robots: "index, follow"

base: '.'

fonts:
    - "https://fonts.googleapis.com/css2?family=Brush+Script"
    - "https://fonts.googleapis.com/css2?family=Kalam:wght@400;700&display=swap"

css:
  - "/css/main.css"
  - "/css/article.css"
  - "/css/content.css"
  - "/css/display_table.css"
  - "/css/header.css"
  - "/css/message_box.css"
  - "/css/menu.css"


js:
  - "/js/main.js"
  - "https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"
  - "https://cdnjs.cloudflare.com/ajax/libs/js-yaml/4.1.0/js-yaml.min.js"

keywords:
  - hypnosis
  - astrology
  - technology
  - ruby
  - python
  - perl
  - bash
  - linux
  - html
  - css
  - javascript

menus:
  main_menu:
    "Home": "/html/main/home.html"
    "GoFundMe": "/html/main/go_fund_me.html"
    "Hypnosis":
      "Professional Experience": "/html/articles/hypnosis/bhc.html"
      "About Hypnosis": "/html/hypnosis/about_hypnosis.html"
      "Hypnosis Services": "/html/hypnosis/hypnosis_services.html"
      "Testimonals": "/html/hypnosis/testimonals.html"
      "Anger": "/html/hypnosis/anger.html"
      "Weight Loss": "/html/hypnosis/weight_loss.html"
      "Smoking Cessation": "/html/hypnosis/smoking_cessation.html"
    "Addiction Services": "/html/addiction/addiction_services.html"
    "Astrology": "/html/astrology/astrology.html"
    "Handwriting Analysis": "/html/graphology/graphology.html"
    "Technology":
      "Projects": "/html/technology/projects.html"
      "Artwork": "/html/technology/artwork.html"
      "Resume": "/html/technology/resume.html"
    "Upcoming Events": "/html/main/upcoming_events.html"
    "Articles": "/html/articles/articles.html"
    "Contact Us": "/html/main/contact_us.html"

data:
  address:
    street: "Coming Soon"
    city: "South Jersey"
    state: "NJ"
    zipcode: "08104"
  phone: "(856) 209-3350"
  email: "afistler.services@gmail.com"
  footer:
    - "Copyright © 2023 - Adam Fistler Services"
    - "Adam Fistler Services - New Office Coming Soon (856) 209-3350"
    - "Serving South Jersey with the latest in hypnosis, addiction alternatives, mindfullness and technology."
    - "South Jersey's Choice for Holisitc Healing"

