site_dir: "#{cinnamon_dir}/sites"
user_dir: "${HOME}/cinnamon_dev"
user_config_dir: "#{user_dir}/config"
user_site_dir: "#{user_dir}/sites"
input_dir: "#{user_dir}/input"
output_dir: "#{user_dir}/output"
