system_site_directory: "#{system_cinnamon_directory}/sites"
user_directory: "${HOME}/cinnamon_dev"
user_config_directory: "#{user_directory}/config"
user_site_directory: "#{user_directory}/sites"
input_directory: "#{user_directory}/input"
output_directory: "#{user_directory}/output"

