extensions:
  metadata:
    - yaml
  image:
    - jpeg
    - jpg
    - jfif
    - png
    - gif
    - webp
    - svg
    - bmp
    - tiff
    - tif
    - ico
    - heif
    - heic
  page:
    - html
    - htm
    - md
    - markdown
  css:
    - css
    - scss
    - sass
    - less
  js:
    - js
  widget:
    - wdg
  template:
    - tem
  video:
    - mp4
    - webm
    - ogv
    - avi
    - mov
    - mkv
    - flv
    - mpeg
    - wmv
    - 3gp
  audio:
    - mp3
    - ogg
    - wav
    - flac
    - aac
    - wma
    - m4a
    - opus
    - mid
    - afif
    - mod
    - s3m
  font:
    - ttf
    - woff
    - woff2
  file:
    - doc
    - docx
    - pdf
    - xls
    - xlsx
    - ppt
    - pptx
    - csv
    - yaml
    - json
    - xml
    - py
    - rb
    - pl
    - php
    - asp
    - aspx
    - sh
    - ps1
    - bat
    - ini
    - cfg
    - conf
    - env
    - gitignore
    - gitattributes
    - sql
    - json
    - yml
    - ejs
    - handlebars
    - mustache
    - log
    - txt
    - bak
    - backup
    - bat
    - sh
    - bash
    - exe
    - msi
    - vagrantfile
    - dockerfile
    - crt
    - pem
    - ai
    - obj
    - stl
    - fbx
    - psd
